-- 33. Выбрать все данные об обучающихся, которые не сдали только один курс из имеющихся в базе данных. 
EXPLAIN (
	ANALYZE,
	BUFFERS,
	VERBOSE
)
SELECT
	S.STUDENTID,
	S.FIRSTNAME,
	S.SECONDNAME,
	S.NIKENAME
FROM
	STUDENT S
	JOIN (
		SELECT
			SP.STUDENTID
		FROM
			STUDENTPERFORMANCE SP
			RIGHT JOIN COURSE C ON C.COURSEID = SP.COURSEID
		GROUP BY
			SP.STUDENTID
		HAVING
			COUNT(C.COURSEID) - COUNT(
				CASE
					WHEN SP.MARKS >= 3 THEN 1
				END
			) = 1
	) AS T ON S.STUDENTID = T.STUDENTID
ORDER BY
	S.SECONDNAME,
	S.FIRSTNAME;

------------------------------------------------------------------------------------
EXPLAIN (
	ANALYZE,
	BUFFERS,
	VERBOSE
)
SELECT
	S.STUDENTID,
	S.FIRSTNAME,
	S.SECONDNAME,
	S.NIKENAME
FROM
	STUDENT S
	LEFT JOIN STUDENTPERFORMANCE SP ON S.STUDENTID = SP.STUDENTID
	LEFT JOIN COURSE C ON C.COURSEID = SP.COURSEID
GROUP BY
	S.STUDENTID,
	S.FIRSTNAME,
	S.SECONDNAME,
	S.NIKENAME
HAVING
	COUNT(C.COURSEID) - COUNT(
		CASE
			WHEN SP.MARKS >= 3 THEN 1
		END
	) = 1
ORDER BY
	S.SECONDNAME,
	S.FIRSTNAME;

--==========================================================================
--44. Выбрать для каждого преподавателя количество курсов, которые он преподает,и общее количество курсов, которые есть в БД.
EXPLAIN (
	ANALYZE,
	BUFFERS,
	VERBOSE
)
SELECT
	T.TEACHERID,
	T.LASTNAME,
	T.FIRSTNAME,
	T.MIDDLENAME,
	COUNT(DISTINCT CT.COURSEID) AS AMOUNT_COURSES_TEACHER,
	(
		SELECT
			COUNT(*)
		FROM
			COURSE
	) AS WHOLE_AMOUNT_COURSES_DATABASE
FROM
	TEACHER T
	LEFT JOIN LESSON L ON T.TEACHERID = L.TEACHERID
	LEFT JOIN COURSETHEME CT ON L.THEMEID = CT.THEMEID
GROUP BY
	T.TEACHERID,
	T.LASTNAME,
	T.FIRSTNAME,
	T.MIDDLENAME
ORDER BY
	AMOUNT_COURSES_TEACHER DESC,
	T.LASTNAME;

----------------
EXPLAIN (
	ANALYZE,
	BUFFERS,
	VERBOSE
)
SELECT
	T.TEACHERID,
	T.LASTNAME,
	T.FIRSTNAME,
	T.MIDDLENAME,
	COUNT(DISTINCT CT.COURSEID) AS AMOUNT_COURSES_TEACHER,
	C.TOTAL_COURSES AS WHOLE_AMOUNT_COURSES_DATABASE
FROM
	TEACHER T
	LEFT JOIN LESSON L ON T.TEACHERID = L.TEACHERID
	LEFT JOIN COURSETHEME CT ON L.THEMEID = CT.THEMEID
	CROSS JOIN (
		SELECT
			COUNT(*) AS TOTAL_COURSES
		FROM
			COURSE
	) C
GROUP BY
	T.TEACHERID,
	T.LASTNAME,
	T.FIRSTNAME,
	T.MIDDLENAME,
	C.TOTAL_COURSES
ORDER BY
	AMOUNT_COURSES_TEACHER DESC,
	T.LASTNAME;

--==========================================================================
-- 41. Выбрать курс, который сдало наибольшее количество человек.
EXPLAIN (
	ANALYZE,
	BUFFERS,
	VERBOSE
)
SELECT
	C.COURSEID,
	C.NAME,
	COUNT(DISTINCT SP.STUDENTID) AS PASS_STUDENT
FROM
	COURSE C
	JOIN STUDENTPERFORMANCE SP ON C.COURSEID = SP.COURSEID
WHERE
	SP.MARKS >= 3
GROUP BY
	C.COURSEID,
	C.NAME
ORDER BY
	PASS_STUDENT DESC;

---------------------------------------------------------------
EXPLAIN (
	ANALYZE,
	BUFFERS,
	VERBOSE
)
WITH
	COURSEPASSCOUNTS AS (
		SELECT
			C.COURSEID,
			C.NAME,
			COUNT(DISTINCT SP.STUDENTID) AS PASSEDSTUDENTS
		FROM
			COURSE C
			JOIN STUDENTPERFORMANCE SP ON C.COURSEID = SP.COURSEID
		WHERE
			SP.MARKS >= 3
		GROUP BY
			C.COURSEID,
			C.NAME
	)
SELECT
	*
FROM
	COURSEPASSCOUNTS
WHERE
	PASSEDSTUDENTS = (
		SELECT
			MAX(PASSEDSTUDENTS)
		FROM
			COURSEPASSCOUNTS
	);